---
items:
- kind: customsearch#result
  title: New Zealand pilot test – Project Loon – Google
  htmlTitle: New Zealand pilot <b>test</b> – Project Loon – Google
  link: https://www.google.com/intl/en-US/loon/where/
  displayLink: www.google.com
  snippet: "Google began its Project Loon pilot test on June 15, 2013 when a dozen
    or so \nballoons were launched from New Zealand's South Island. These balloons
    \ndelivered Internet service at 3G speeds to several pilot testers in the Canterbury
    \narea."
  htmlSnippet: |-
    Google began its Project Loon pilot <b>test</b> on June 15, 2013 when a dozen or so <br>
    balloons were launched from New Zealand&#39;s South Island. These balloons <br>
    delivered Internet service at 3G speeds to several pilot testers in the Canterbury <br>
    area.
  cacheId: F3AVyDQUxmEJ
  formattedUrl: https://www.google.com/intl/en-US/loon/where/
  htmlFormattedUrl: https://www.google.com/intl/en-US/loon/where/
  pagemap:
    cse_thumbnail:
    - width: '239'
      height: '211'
      src: https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRVAZHIAA8Anc_fqVX-cTtgEB_4F4h0o_AcesX8RuqcFV5BddFuttYK551C
    metatags:
    - viewport: initial-scale=1, minimum-scale=1, width=device-width
    webpage:
    - name: Project Loon
      description: Balloon-Powered Internet For Everyone
      image: "../../loon/images/snippet.png"
    cse_image:
    - src: https://www.google.com/intl/en-US/loon/images/where-globe/seq-1.png
- kind: customsearch#result
  title: AB & Multivariate Testing Tool Features - Google Optimize
  htmlTitle: AB &amp; Multivariate <b>Testing</b> Tool Features - Google Optimize
  link: https://www.google.com/analytics/optimize/features/
  displayLink: www.google.com
  snippet: "Google Optimize features include A/B/n testing, multivariate testing,
    and redirect \ntesting to personalize your website for each customer's experience."
  htmlSnippet: |-
    Google Optimize features include A/B/n <b>testing</b>, multivariate <b>testing</b>, and redirect <br>
    <b>testing</b> to personalize your website for each customer&#39;s experience.
  cacheId: lTOFh5XME_UJ
  formattedUrl: https://www.google.com/analytics/optimize/features/
  htmlFormattedUrl: https://www.google.com/analytics/optimize/features/
  pagemap:
    metatags:
    - viewport: initial-scale=1, minimum-scale=1, width=device-width
- kind: customsearch#result
  title: US6266562B1 - Defibrillator with automated test load - Google Patents
  htmlTitle: US6266562B1 - Defibrillator with automated <b>test</b> load - Google
    Patents
  link: https://www.google.com/patents/US6266562
  displayLink: www.google.com
  snippet: "A defibrillator is provided with a test load feature which is automatically
    inserted \ninto electrode paddle jacks when a defibrillator housing lid is closed,
    placing the \ndefibrillator controller into a TEST MODE. Closing the lid permits
    actual firing of a \nshock pulse through the electrode connector through the test
    load, opening the ..."
  htmlSnippet: |-
    A defibrillator is provided with a <b>test</b> load feature which is automatically inserted <br>
    into electrode paddle jacks when a defibrillator housing lid is closed, placing the <br>
    defibrillator controller into a <b>TEST</b> MODE. Closing the lid permits actual firing of a <br>
    shock pulse through the electrode connector through the <b>test</b> load, opening the&nbsp;...
  formattedUrl: https://www.google.com/patents/US6266562
  htmlFormattedUrl: https://www.google.com/patents/US6266562
  pagemap:
    cse_thumbnail:
    - width: '94'
      height: '120'
      src: https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQJtp80YsU97U7BHR-X8hCE1BvxyUnLSt4iZAQXiWiODdN_mHtV01gEGA
    metatags:
    - viewport: width=device-width, initial-scale=1
      referrer: origin-when-crossorigin
      dc.type: patent
      dc.title: Defibrillator with automated test load
      dc.date: '1999-04-30'
      dc.description: A defibrillator is provided with a test load feature which is
        automatically inserted into electrode paddle jacks when a defibrillator housing
        lid is closed, placing the defibrillator controller into a TEST MODE. Closing
        the lid permits actual firing of a shock pulse through the electrode connector
        through the test load, opening the lid automatically disconnects the test
        load and permits insertion of electrode paddles, placing the defibrillator
        into a PATIENT-READY MODE.
      citation_patent_application_number: US:09/302,558
      citation_pdf_url: https://patentimages.storage.googleapis.com/7f/49/3c/422b128b853d1d/US6266562.pdf
      citation_patent_number: US:6266562
      dc.contributor: Kent W. Leyde
      dc.relation: US:4628935
    cse_image:
    - src: https://patentimages.storage.googleapis.com/thumbnails/US6266562B1/US06266562-20010724-D00002.png
- kind: customsearch#result
  title: 140th Anniversary of the First Cricket Test Match
  htmlTitle: 140th Anniversary of the First Cricket <b>Test</b> Match
  link: http://www.google.com/doodles/140th-anniversary-of-the-first-cricket-test-match
  displayLink: www.google.com
  snippet: "Mar 15, 2017 ... 140th Anniversary of the First Cricket Test Match. The
    first officially-recognized \ntest cricket match took place 140 years ago today.
    It was a contest between the \nestablished English side and the newly-formed Australian
    team. Australia won \nthe first match, but England won the second match to draw
    the series ..."
  htmlSnippet: |-
    Mar 15, 2017 <b>...</b> 140th Anniversary of the First Cricket <b>Test</b> Match. The first officially-recognized <br>
    <b>test</b> cricket match took place 140 years ago today. It was a contest between the <br>
    established English side and the newly-formed Australian team. Australia won <br>
    the first match, but England won the second match to draw the series&nbsp;...
  cacheId: gdqmC48OwfEJ
  formattedUrl: www.google.com/.../140th-anniversary-of-the-first-cricket-test-match
  htmlFormattedUrl: www.google.com/.../140th-anniversary-of-the-first-cricket-<b>test</b>-match
  pagemap:
    cse_thumbnail:
    - width: '337'
      height: '150'
      src: https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTTP3C8MmwRkb1BB1Nir6JPC6RcWRNAIWyT-CRRlWKlRP3yKR7cjH0IT4Ld
    metatags:
    - og:title: 140th Anniversary of the First Cricket Test Match
      twitter:card: summary_large_image
      twitter:site: "@GoogleDoodles"
      twitter:title: 140th Anniversary of the First Cricket Test Match
      og:image: http://www.google.com/logos/doodles/2017/140th-anniversary-of-the-first-cricket-test-match-5659058039160832-hp2x.png
      twitter:image: http://www.google.com/logos/doodles/2017/140th-anniversary-of-the-first-cricket-test-match-5659058039160832-hp2x.png
      og:image:width: '900'
      og:image:height: '400'
      og:type: website
      og:description: '140th Anniversary of the First Cricket Test Match #GoogleDoodle'
      twitter:description: '140th Anniversary of the First Cricket Test Match #GoogleDoodle'
    cse_image:
    - src: http://www.google.com/logos/doodles/2017/140th-anniversary-of-the-first-cricket-test-match-5659058039160832-hp2x.png
- kind: customsearch#result
  title: Website Testing to Improve Customer Experiences - Google ...
  htmlTitle: Website <b>Testing</b> to Improve Customer Experiences - Google ...
  link: https://www.google.com/analytics/resources/webinar-test-with-success-even-when-you-fail.html
  displayLink: www.google.com
  snippet: "Building a better website means testing everything. Website testing not
    only \nimproves web experiences, it's also key to building a culture of growth
    — one \nwhere everyone gathers and acts on data-based insights to optimize the
    \ncustomer experience day by day. In a growth culture, honing your team's ability
    to \ndesign and ..."
  htmlSnippet: |-
    Building a better website means <b>testing</b> everything. Website <b>testing</b> not only <br>
    improves web experiences, it&#39;s also key to building a culture of growth — one <br>
    where everyone gathers and acts on data-based insights to optimize the <br>
    customer experience day by day. In a growth culture, honing your team&#39;s ability to <br>
    design and&nbsp;...
  cacheId: OH3AG6-3CIsJ
  formattedUrl: https://www.google.com/.../webinar-test-with-success-even-when-you-fail.
    html
  htmlFormattedUrl: https://www.google.com/.../webinar-<b>test</b>-with-success-even-when-you-fail.
    html
  pagemap:
    metatags:
    - viewport: initial-scale=1, minimum-scale=1, width=device-width
- kind: customsearch#result
  title: Website, AB Testing & Personalization Solutions - Google Optimize
  htmlTitle: Website, AB <b>Testing</b> &amp; Personalization Solutions - Google Optimize
  link: https://www.google.com/analytics/optimize/
  displayLink: www.google.com
  snippet: "Google Optimize offers AB testing, website testing & personalization tools
    for \nsmall & large enterprises to help deliver engaging customer experiences."
  htmlSnippet: |-
    Google Optimize offers AB <b>testing</b>, website <b>testing</b> &amp; personalization tools for <br>
    small &amp; large enterprises to help deliver engaging customer experiences.
  cacheId: CHi8gnG9rB0J
  formattedUrl: https://www.google.com/analytics/optimize/
  htmlFormattedUrl: https://www.google.com/analytics/optimize/
  pagemap:
    metatags:
    - viewport: initial-scale=1, minimum-scale=1, width=device-width
- kind: customsearch#result
  title: Robots TXT testing tool
  htmlTitle: Robots TXT <b>testing</b> tool
  link: https://www.google.com/webmasters/tools/robots-testing-tool
  displayLink: www.google.com
  snippet: Use Search Console to monitor Google Search results data for your properties.
  htmlSnippet: Use Search Console to monitor Google Search results data for your properties.
  cacheId: SEobM4kUT5EJ
  formattedUrl: https://www.google.com/webmasters/tools/robots-testing-tool
  htmlFormattedUrl: https://www.google.com/webmasters/tools/robots-<b>testing</b>-tool
  pagemap:
    metatags:
    - viewport: width=device-width, initial-scale=1
- kind: customsearch#result
  title: US7786854B2 - Alarm system walk test - Google Patents
  htmlTitle: US7786854B2 - Alarm system walk <b>test</b> - Google Patents
  link: https://www.google.com/patents/US7786854
  displayLink: www.google.com
  snippet: "A system and method for performing a walk test for an alarm system having
    an \nalarm panel and at least one zone, each zone having at least one sensor,
    having \nsteps of placing the alarm panel in an engineering mode, establishing
    a \ncommunications channel between the alarm panel and a communication device
    \nand ..."
  htmlSnippet: |-
    A system and method for performing a walk <b>test</b> for an alarm system having an <br>
    alarm panel and at least one zone, each zone having at least one sensor, having <br>
    steps of placing the alarm panel in an engineering mode, establishing a <br>
    communications channel between the alarm panel and a communication device <br>
    and&nbsp;...
  formattedUrl: https://www.google.com/patents/US7786854
  htmlFormattedUrl: https://www.google.com/patents/US7786854
  pagemap:
    cse_thumbnail:
    - width: '121'
      height: '120'
      src: https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQPasI-uD4h714CUq4gdWe7Ax-HTH3WNP44vvIG2FkDXvkpCgfrCdIt
    metatags:
    - viewport: width=device-width, initial-scale=1
      referrer: origin-when-crossorigin
      dc.type: patent
      dc.title: Alarm system walk test
      dc.date: '2008-01-17'
      dc.description: A system and method for performing a walk test for an alarm
        system having an alarm panel and at least one zone, each zone having at least
        one sensor, having steps of placing the alarm panel in an engineering mode,
        establishing a communications channel between the alarm panel and a communication
        device and remotely placing the alarm panel in an appropriate state for each
        walk test, selecting a zone, triggering an alarm for each sensor in the selected
        zone, and using the communications channel to report the triggered alarm to
        the communication device, and remotely placing the alarm panel in an appropriate
        state for the next walk test after triggering all of the sensors in the zone.
        The system and method can also include user input to the alarm panel to indicate
        the desired communications channel.
      citation_patent_application_number: US:12/015,679
      citation_pdf_url: https://patentimages.storage.googleapis.com/9e/bc/90/2b08a046121e6d/US7786854.pdf
      citation_patent_number: US:7786854
      dc.contributor: Mark Hosey
      dc.relation: US:4725818
    cse_image:
    - src: https://patentimages.storage.googleapis.com/thumbnails/US7786854B2/US07786854-20100831-D00001.png
- kind: customsearch#result
  title: US6087089A - Peroxide and chlorine test strip - Google Patents
  htmlTitle: US6087089A - Peroxide and chlorine <b>test</b> strip - Google Patents
  link: https://www.google.com/patents/US6087089
  displayLink: www.google.com
  snippet: "A composition, method, and test device for quantitatively determining
    the oxidant \nconcentration of a test sample are disclosed. The test device includes
    a test pad \nhaving a suitable carrier matrix incorporating an indicator reagent
    composition \ncapable of interacting with an oxidant to produce a detectable and
    measurable ..."
  htmlSnippet: |-
    A composition, method, and <b>test</b> device for quantitatively determining the oxidant <br>
    concentration of a <b>test</b> sample are disclosed. The <b>test</b> device includes a <b>test</b> pad <br>
    having a suitable carrier matrix incorporating an indicator reagent composition <br>
    capable of interacting with an oxidant to produce a detectable and measurable&nbsp;...
  formattedUrl: https://www.google.com/patents/US6087089
  htmlFormattedUrl: https://www.google.com/patents/US6087089
  pagemap:
    cse_thumbnail:
    - width: '82'
      height: '120'
      src: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0Hr9Y6Z2wBr7ChHJJvn_m-Wd9HWsf5F9xMTBRcP9uKfbqBs3m0aeb
    metatags:
    - viewport: width=device-width, initial-scale=1
      referrer: origin-when-crossorigin
      dc.type: patent
      dc.title: Peroxide and chlorine test strip
      dc.date: '1998-06-02'
      dc.description: 'A composition, method, and test device for quantitatively determining
        the oxidant concentration of a test sample are disclosed. The test device
        includes a test pad having a suitable carrier matrix incorporating an indicator
        reagent composition capable of interacting with an oxidant to produce a detectable
        and measurable response for oxidant over a wide concentration range of oxidant.
        An indicator reagent composition contains: (a) an iodide salt, (b) a buffer,
        and (c) a water-soluble polymer, preferably a cellulose-based polymer. An
        indicator reagent composition is incorporated into a carrier matrix, like
        filter paper, to provide a test pad useful in a dry phase oxidant assay of
        a test sample, especially for test samples containing a high concentration
        of oxidant, like chlorine or a peroxide.'
      citation_patent_application_number: US:09/088,741
      citation_pdf_url: https://patentimages.storage.googleapis.com/08/4f/40/829076a7eb51ac/US6087089.pdf
      citation_patent_number: US:6087089
      dc.contributor: Wen H. Wu
      dc.relation: US:3814668
      citation_reference: Bottle Label, Renalin Perassay 500, Renal Systems, Minneapolis,
        MN.
    cse_image:
    - src: https://patentimages.storage.googleapis.com/thumbnails/pages/US6087089-3.png
- kind: customsearch#result
  title: US7930683B2 - Test automation method for software programs ...
  htmlTitle: US7930683B2 - <b>Test</b> automation method for software programs ...
  link: https://www.google.com/patents/US7930683
  displayLink: www.google.com
  snippet: "A method for testing a software program creates test data by simulating
    data \nexchange messages between a server and a client and stores test data in
    \nComma Separated Value (CSV) files. Data repository files stored in the CSV \nformat
    can be edited by common tools, like a spreadsheet program, and can be \nmaintained ..."
  htmlSnippet: |-
    A method for <b>testing</b> a software program creates <b>test</b> data by simulating data <br>
    exchange messages between a server and a client and stores <b>test</b> data in <br>
    Comma Separated Value (CSV) files. Data repository files stored in the CSV <br>
    format can be edited by common tools, like a spreadsheet program, and can be <br>
    maintained&nbsp;...
  formattedUrl: https://www.google.com/patents/US7930683
  htmlFormattedUrl: https://www.google.com/patents/US7930683
  pagemap:
    cse_thumbnail:
    - width: '133'
      height: '120'
      src: https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRWkd0nEhmbDnRS4DSSW1JnH40xcKidcQuPEI7OGebxs3yxtnKtZ6LoGA
    metatags:
    - viewport: width=device-width, initial-scale=1
      referrer: origin-when-crossorigin
      dc.type: patent
      dc.title: Test automation method for software programs
      dc.date: '2006-03-31'
      dc.description: A method for testing a software program creates test data by
        simulating data exchange messages between a server and a client and stores
        test data in Comma Separated Value (CSV) files. Data repository files stored
        in the CSV format can be edited by common tools, like a spreadsheet program,
        and can be maintained easily. The test automation method provides a data capturer
        tool so that the data repository could be created based on any existing test
        environment. The test automation method converts data repository files and
        simulates messages in order to load data to a mobile infrastructure system
        and set up data fixtures. The test automation method could be integrated in
        a build process so that data repository and test cases are validated against
        any program changes periodically.
      citation_patent_application_number: US:11/394,559
      citation_pdf_url: https://patentimages.storage.googleapis.com/c7/89/e7/e09cdfaf4ec20c/US7930683.pdf
      citation_patent_number: US:7930683
      dc.contributor: Chunyue Li
      dc.relation: US:4519078
      citation_reference: Berner, Stefan et al., "Observations and Lessons Learned
        from Automated Testing," In Proceedings of the 27th International Conference
        on Software Engineering (ICSE'05), May 15-21, 2005., St. Louis Missouri, USA,
        pp. 571-579.
    cse_image:
    - src: https://patentimages.storage.googleapis.com/thumbnails/US7930683B2/US07930683-20110419-D00006.png